### ISSUE TITLE
Is this pasted?

### ISSUE THREAD

**Issue by userinfected** [Parritz/luapacker#1]
This is pasted, whats the point? You even forgot to remove the original name in the CLI "lua-pack" https://github.com/Bork0038/lua-pack

**Comment by Parritz** [comment]
Every line of code here has been written by me and can be seen through every commit I've made. In fact, I don't even use the same parsing method as lua-pack. While lua-pack by Bork is great, it has a few flaws, which is why this was made.

For example, lua-pack uses Luaparse. Why is this bad? This means it doesn't support Luau features. I wanted to make a much simpler method of combining Lua files that didn't interfere with Luau features, hence why this was made.

As for your argument of "forgetting to remove the original name," I believe you're referring to the "lpk" cmd, which is just a shortened version of the cmd for people who don't want to type "luapacker" every time. Not that lua-pack by Bork uses this cmd anyways.

**Comment by userinfected** [comment]
My bad, I somehow got the directories mixed, the actual lua-pack src was in my luapacker folder. I am looking forward to new updates to luapacker. You should consider a more unique name that sets it apart. 👍
